# select base image
FROM node:alpine

WORKDIR '/app'

# install all dependencies
COPY package.json .
RUN npm install

# copy the rest of project
COPY . .

# start project
CMD ["npm", "run", "serve"]

